#!/bin/bash

# Real Estate Portal - Render.com Deployment Script

echo "🚀 Real Estate Portal - Render.com Deployment"
echo "=============================================="

echo ""
echo "Render.com is often more reliable than Railway for Node.js apps."
echo ""

echo "📋 Deployment Steps:"
echo ""
echo "1. Go to https://render.com and sign up with GitHub"
echo ""
echo "2. Click 'New +' → 'Web Service'"
echo ""
echo "3. Connect your GitHub repository"
echo ""
echo "4. Configure:"
echo "   - Name: real-estate-backend"
echo "   - Root Directory: backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: node server.js"
echo "   - Plan: Free (or Starter for better performance)"
echo ""
echo "5. Click 'Advanced' and add Environment Variables:"
echo "   NODE_ENV=production"
echo "   JWT_SECRET=<generate-32-char-random-string>"
echo "   FRONTEND_URL=https://your-frontend.vercel.app"
echo "   RAZORPAY_KEY_ID=<your-key>"
echo "   RAZORPAY_KEY_SECRET=<your-secret>"
echo "   EMAIL_HOST=smtp.gmail.com"
echo "   EMAIL_PORT=587"
echo "   EMAIL_USER=<your-email>"
echo "   EMAIL_PASSWORD=<your-app-password>"
echo ""
echo "6. Create PostgreSQL Database:"
echo "   - Click 'New +' → 'PostgreSQL'"
echo "   - Name: real-estate-db"
echo "   - Plan: Free"
echo "   - Click 'Create Database'"
echo ""
echo "7. Link Database to Web Service:"
echo "   - Go back to your web service"
echo "   - In Environment tab, add:"
echo "   DATABASE_URL=<copy Internal Database URL from PostgreSQL service>"
echo ""
echo "8. Deploy!"
echo ""
echo "🎉 Your backend will be live at: https://your-app.onrender.com"
echo ""
echo "📝 Note: Free tier services sleep after 15 min of inactivity"
echo "    Consider Starter plan ($7/month) for production use"
echo ""

read -p "Press Enter to open Render.com..."
xdg-open https://render.com 2>/dev/null || open https://render.com 2>/dev/null || echo "Please visit: https://render.com"
